name: Mise a jour des donnees

on:
  schedule:
    - cron: '0 4 * * *' # Roule à 4h du matin chaque jour
  workflow_dispatch:      # Permet de le lancer manuellement pour tester

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer les librairies
        run: pip install -r requirements.txt

      - name: Lancer le scraper
        run: python scraper.py

      - name: Sauvegarder les changements
        run: |
          git config --global user.name 'Scraper Bot'
          git config --global user.email 'bot@github.com'
          git add evenements.json
          git commit -m "Mise à jour automatique des événements" || exit 0
          git push
